Document `pending_transaction_verify` endpoint
helium/blockchain-node pull request #115
Opened 2022-01-28 15:59 UTC by lthiery

2022-01-28 17:39 UTC, abhay approved these changes
❤️ docs

2022-01-31 13:27 UTC, madninja requested changes
This does not actually create the documentation. To keep it simple we leave the docs right in this repo, which makes you need to have the required packages installed, and run `make docs` . The generated html and md should be checked in with this PR

2022-01-31 23:02 UTC, lthiery commented
Noticed a small mistake on the submit_txn that I inherited:

![image](https://user-images.githubusercontent.com/1606640/151887375-cf684969-4361-48c7-864d-0b147dbeb22e.png)

Corrected here, it looks like this:
![image](https://user-images.githubusercontent.com/1606640/151887246-da6675e1-207e-42df-bc87-22d939aa0e48.png)

2022-01-31 23:26 UTC, madninja approved these changes

2022-01-31 23:26 UTC, merged