Update for validators testnet.
helium/blockchain-node pull request #12
Opened 2021-03-08 01:19 UTC by ke6jjj

Add the ability to configure the `libp2p` network to something other than `mainnet`,
if overridden by `sys.config`.

These changes should allow a node to follow the validators testnet (or any other
future net, for that matter).

2021-03-10 14:00 UTC, madninja commented on config/val.config
> + "config/sys.config",
This should really just be a testnet.config and override for sys.config not completely replacing all the below. That is, if we actually ever want to support testnet in the repo going forward. 

I don't think we should but at least the network setting in the sup and a bumped libp2p and core to pick up the crypto changes in v1.3.3 would be great

2021-03-10 14:00 UTC, madninja commented on src/bn_sup.erl
> +    ok = libp2p_crypto:set_network(application:get_env(blockchain, network, mainnet)),
This is really the only fix we want beyond an upgraded core once that lands in master

2021-03-10 19:31 UTC, madninja commented
Just missing setting the network type on startup?

2021-03-10 19:33 UTC, ke6jjj commented
I'm not sure what that means? It has to be set in the config somewhere, but we don't want to check in a config in this PR, correct? That means this is the only change in the PR.

2021-03-10 20:00 UTC, madninja commented
Yeah I missed the patch bit where crypto:set_network is called. all good

On Wed, Mar 10, 2021 at 1:33 PM Jeremy Cooper <notifications@github.com>
wrote:

> I'm not sure what that means? It has to be set in the config somewhere,
> but we don't want to check in a config in this PR, correct? That means this
> is the only change in the PR.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/helium/blockchain-node/pull/12#issuecomment-795964007>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAACZBVHG5OJLHW2GH6I6D3TC63PTANCNFSM4YYPHLBQ>
> .
>

2021-03-11 12:58 UTC, madninja requested changes
While you updated the core tag the git reference in the lockfile appears _not_ to be pointing at that tagged commit on master

2021-03-17 12:07 UTC, madninja approved these changes

2021-03-17 12:08 UTC, merged