Changes for Rosetta API
helium/blockchain-node pull request #39
Opened 2021-08-01 02:27 UTC by syuan100

- Implicit burn endpoint
- Peers endpoint
- Snapshot + core bump
- Dev implicit_burn config
- Rosetta Docker config

2021-08-01 02:33 UTC, syuan100 commented
@abhay This is the final piece of the puzzle for the Rosetta API, and then we'll have no more forked deps. Let me know what y'all think

2021-08-04 20:02 UTC, abhay commented
> @abhay This is the final piece of the puzzle for the Rosetta API, and then we'll have no more forked deps. Let me know what y'all think

Is the peers RPC required in this implementation?

2021-08-04 20:03 UTC, abhay commented
@madninja curious on your thoughts of always storing implicit burns in `blockchain-node`? Seems useful for wallet / light nodes.

2021-08-04 20:07 UTC, madninja commented
> @madninja curious on your thoughts of always storing implicit burns in `blockchain-node`? Seems useful for wallet / light nodes.

We need this for both etl and node actually.. but I'd rather not have all of rosetta to have it? is that even possible?

2021-08-04 20:14 UTC, syuan100 commented
> > @abhay This is the final piece of the puzzle for the Rosetta API, and then we'll have no more forked deps. Let me know what y'all think
> 
> Is the peers RPC required in this implementation?

For the `/network/status` endpoint it is. I just included the bulk of the implementation from miner intact in case it might be useful in the future. I can pare it down to only what's necessary though.

2021-08-04 20:17 UTC, madninja commented
> > > @abhay This is the final piece of the puzzle for the Rosetta API, and then we'll have no more forked deps. Let me know what y'all think
> > 
> > 
> > Is the peers RPC required in this implementation?
> 
> For the `/network/status` endpoint it is. I just included the bulk of the implementation from miner intact in case it might be useful in the future. I can pare it down to only what's necessary though.

Who is that useful for though? If it's just for helpful debugging maybe don't include it in this PR?

2021-08-04 20:20 UTC, syuan100 commented
Sure I'll update later this afternoon to cleanup the peers endpoint

2021-08-04 20:22 UTC, syuan100 commented
> > @madninja curious on your thoughts of always storing implicit burns in `blockchain-node`? Seems useful for wallet / light nodes.
> 
> We need this for both etl and node actually.. yes
> 
> My initial thinking though was to include the implicit burn in the transaction json itself as well

I'll take a stab and add it as a commit.

2021-08-05 01:36 UTC, syuan100 commented
@abhay @madninja updated per the notes above. Tested locally and it works properly, however there is one codepath I'm not able to test which is: https://github.com/helium/blockchain-node/blob/master/src/bn_txns.erl#L133

Essentially, it looks like there is a JsonCF where txn data lives, but in the case that it's not there we go grab the actual txn and then parse it into json. I haven't been able to find a transaction that isn't found in the JsonCF so wanted to ask to see how I might be able to trigger it.

2021-08-05 12:05 UTC, madninja commented
> Essentially, it looks like there is a JsonCF where txn data lives, but in the case that it's not there we go grab the actual txn and then parse it into json. I haven't been able to find a transaction that isn't found in the JsonCF so wanted to ask to see how I might be able to trigger it.

That codepath was for blockchain-node instances that were running _before_ the jsoncf column family was added. It ensures that if jsoncf doesn't have it but the transaction exists that it is still returned as correctly as we can

2021-08-05 18:50 UTC, abhay commented
> @abhay @madninja updated per the notes above. Tested locally and it works properly

We can probably remove that new overlay config now too right?

2021-08-05 20:45 UTC, syuan100 commented
> > @abhay @madninja updated per the notes above. Tested locally and it works properly
> 
> We can probably remove that new overlay config now too right?

Sooo rosetta requires the data dir to be at `/data`... so while it's only a one line change I still need the docker rosetta config. devib has been removed though.

2021-08-05 21:19 UTC, syuan100 commented
> That codepath was for blockchain-node instances that were running _before_ the jsoncf column family was added. It ensures that if jsoncf doesn't have it but the transaction exists that it is still returned as correctly as we can

ok I was able to test it just by commenting out the JsonCF codepath and forcing the node to pull the actual txn. Works accordingly

2021-08-10 03:31 UTC, syuan100 commented
Hey Helium team, I also included new testnet configs on a separate branch since I want to do more rigorous testing for more types of transactions. I'm wondering if I should just add it into this branch as part of the PR?

2021-08-10 03:32 UTC, syuan100 commented
I had based it off this branch. Link for reference:
https://github.com/syuan100/blockchain-node/tree/testnet-configs

2021-08-24 06:04 UTC, syuan100 commented
Hi there, I decided to just add the testnet-configs into this PR, as it will help with HTLC transaction testing.

Could possibly be landed before the Wed dewi call? It would be good to have something non-forked in the dockerfile. All good if not, just thought I should ask though.

2021-08-28 01:37 UTC, abhay commented
> Could possibly be landed before the Wed dewi call? It would be good to have something non-forked in the dockerfile. All good if not, just thought I should ask though.

Sorry I missed this. If @madninja is good with it, I'm a 👍🏼

2021-08-28 01:40 UTC, abhay requested changes
updated snapshot to match miner master

2021-08-28 01:40 UTC, abhay commented on config/sys.config
> +        {blessed_snapshot_block_height, 975601},
```suggestion
        {blessed_snapshot_block_height, 983521},
```

2021-08-28 01:40 UTC, abhay commented on config/sys.config
> +            <<87,86,149,234,13,212,196,250,56,57,160,76,150,198,152,134,4,189,17,109,213,98,182,6,194,119,59,127,120,219,229,108>>},
```suggestion
<<97,208,157,201,5,40,83,139,102,73,148,246,147,130,211,30,45,143,70,112,163,70,105,238,101,244,197,179,72,14,100,15>>},
```

2021-08-30 20:01 UTC, madninja commented
Would you mind rebasing on master one more time @syuan100 ? I'll should be able to get it merged this week

2021-09-01 19:46 UTC, syuan100 commented
Rebased and tested, works as expected with latest changes from master

2021-09-06 17:37 UTC, abhay commented
@madninja is this good to go?

2021-09-07 10:53 UTC, madninja approved these changes

2021-09-07 10:53 UTC, merged